#!/usr/bin/env python3
"""Regenerate per-block SHA256 hashes for inline <script> bodies in
frontend/*.html and patch deploy/nginx-security-headers.conf so script-src
whitelists exactly those hashes (instead of 'unsafe-inline').

Run after editing any inline <script> in frontend/*.html:
    python3 scripts/security/regen_csp_hashes.py

Then reload nginx:
    sudo cp deploy/nginx-security-headers.conf /etc/nginx/snippets/biochirp-security-headers.conf
    sudo nginx -t && sudo systemctl reload nginx

The CSP file must contain a `# >>> biochirp-csp-script-src >>>` /
`# <<< biochirp-csp-script-src <<<` marker pair around the
`add_header Content-Security-Policy ...` line. The block between markers
is fully rewritten on each run.

Why hashes (not nonces): chat HTML is served as static files by nginx.
Nonces would require per-request HTML rewriting; hashes are content-addressed
and work on static files. Byte-for-byte edits invalidate the hash — re-run
this script after any inline-script edit.

Inline `<style>` blocks are NOT hashed: pervasive `style=""` attributes mean
style-src must keep 'unsafe-inline' (lower XSS risk than script-src).
"""
from __future__ import annotations

import base64
import glob
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FRONTEND = ROOT / "frontend"
CSP_FILE = ROOT / "deploy" / "nginx-security-headers.conf"

SCRIPT_RX = re.compile(r"<script\b([^>]*)>(.*?)</script\s*>", re.I | re.S)
BEGIN_MARK = "# >>> biochirp-csp-script-src >>>"
END_MARK   = "# <<< biochirp-csp-script-src <<<"


def collect_hashes() -> list[str]:
    hashes: set[str] = set()
    for fp in sorted(glob.glob(str(FRONTEND / "*.html"))):
        txt = Path(fp).read_text(encoding="utf-8", errors="replace")
        for attrs, body in SCRIPT_RX.findall(txt):
            if "src=" in attrs.lower():
                continue
            if not body.strip():
                continue
            digest = hashlib.sha256(body.encode("utf-8")).digest()
            hashes.add("'sha256-" + base64.b64encode(digest).decode() + "'")
    return sorted(hashes)


def build_csp_line(hashes: list[str]) -> str:
    script_src_parts = [
        "'self'",
        *hashes,
        "https://cdn.jsdelivr.net",
        "https://cdn.tailwindcss.com",
    ]
    script_src = "script-src " + " ".join(script_src_parts)
    style_src  = "style-src 'self' 'unsafe-inline'"
    csp = (
        "default-src 'self'; "
        f"{script_src}; "
        f"{style_src}; "
        "img-src 'self' data: blob:; "
        "font-src 'self' data:; "
        "connect-src 'self' ws: wss:; "
        "frame-src https://www.youtube.com https://www.youtube-nocookie.com; "
        "object-src 'none'; "
        "base-uri 'self'; "
        "frame-ancestors 'none'; "
        "form-action 'self'; "
        "upgrade-insecure-requests"
    )
    return f'add_header Content-Security-Policy "{csp}" always;'


def render_block(hashes: list[str]) -> str:
    return (
        f"{BEGIN_MARK}\n"
        f"# AUTOGENERATED by scripts/security/regen_csp_hashes.py — DO NOT EDIT BY HAND.\n"
        f"# {len(hashes)} unique inline <script> hashes across frontend/*.html.\n"
        f"# 'unsafe-inline' is dropped from script-src; kept in style-src because\n"
        f"# pervasive style=\"...\" attributes would otherwise break.\n"
        f"{build_csp_line(hashes)}\n"
        f"{END_MARK}"
    )


def patch_csp_file(hashes: list[str]) -> bool:
    src = CSP_FILE.read_text(encoding="utf-8")
    rendered = render_block(hashes)
    if BEGIN_MARK in src and END_MARK in src:
        new = re.sub(
            re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK),
            rendered,
            src,
            count=1,
            flags=re.S,
        )
    else:
        raise SystemExit(
            f"FATAL: marker pair not found in {CSP_FILE}.\n"
            f"Insert these markers around the CSP add_header line:\n"
            f"  {BEGIN_MARK}\n"
            f"  add_header Content-Security-Policy ... always;\n"
            f"  {END_MARK}"
        )
    if new == src:
        return False
    CSP_FILE.write_text(new, encoding="utf-8")
    return True


def main():
    if not CSP_FILE.is_file():
        print(f"FATAL: {CSP_FILE} missing", file=sys.stderr)
        sys.exit(2)
    hashes = collect_hashes()
    if not hashes:
        print("WARN: no inline scripts found", file=sys.stderr)
    changed = patch_csp_file(hashes)
    print(f"Regenerated {len(hashes)} CSP script hashes.")
    if changed:
        print(f"  -> patched {CSP_FILE.relative_to(ROOT)}")
        print("  Next: sudo cp deploy/nginx-security-headers.conf /etc/nginx/snippets/biochirp-security-headers.conf "
              "&& sudo nginx -t && sudo systemctl reload nginx")
    else:
        print("  CSP file already up to date.")


if __name__ == "__main__":
    main()
