import polars as pl
from utils.dataframe_loader import read_parquet_polars, clean_table_dict
from utils.partner_denorm import auto_add_partner_attributes

# v2 parquets (generated by preprocess.py v2):
#   - All columns are Utf8 at write time (infer_schema_length=0 + cast_all_to_utf8)
#   - Sentinels stripped and null aliases removed at build time
#   - Canonical edge deduplication applied (A→B and B→A collapsed)
#   - gene_symbol1 / gene_symbol2 denormalized into all PPI tables
# Loader-level compensating casts and null-alias filters are no longer required.

def _normalize_ppi_v2(
    lf: pl.LazyFrame,
    gene_col: str,
    partner_col: str,
) -> pl.LazyFrame:
    """Expand canonical undirected parquet rows to bidirectional rows.

    v2 parquets already have final column names (protein_id, <gene_col>,
    protein_partner_id, <partner_col>). We generate the reverse direction by
    swapping protein_id↔protein_partner_id and gene_col↔partner_col so that
    filtering on gene_col=X returns ALL partners of X in partner_col.
    """
    rev = lf.rename({
        "protein_id": "protein_partner_id",
        gene_col: partner_col,
        "protein_partner_id": "protein_id",
        partner_col: gene_col,
    })
    # rev has the same column NAMES as lf but in swapped positions; align by name
    # (how="diagonal") so the vertical stack matches columns by name, not order.
    return pl.concat([lf, rev], how="diagonal")


def return_preprocessed_string() -> dict[str, pl.DataFrame]:
    """Load STRING from the v2 parquets ONLY.

    v1 is decommissioned (archived under database/string/_archive_v1/). All five
    tables read their ``*_v2.parquet`` directly: v2 has the final column names,
    all-Utf8 dtypes (uniform CAST-safety), sentinel/null cleanup, and canonical
    dedup. Master/alias keep the disk ``string_id`` → served ``protein_id``
    rename. PPI tables are expanded to bidirectional rows by _normalize_ppi_v2.
    """
    results = {}

    protein = read_parquet_polars("database", "string", "protein_master_table_string_v2.parquet")
    # Canonical parquet already uses protein_id; conditional rename no-ops there.
    results["protein_master_table_string"] = protein.rename({k: v for k, v in {"string_id": "protein_id"}.items() if k in protein.columns})

    results["ppi_association_string"] = _normalize_ppi_v2(
        read_parquet_polars("database", "string", "ppi_association_string_v2.parquet"),
        gene_col="association_gene_symbol",
        partner_col="association_partner_gene_symbol",
    )

    results["ppi_physical_string"] = _normalize_ppi_v2(
        read_parquet_polars("database", "string", "ppi_physical_string_v2.parquet"),
        gene_col="physical_gene_symbol",
        partner_col="physical_partner_gene_symbol",
    )

    results["ppi_detailed_channels_string"] = _normalize_ppi_v2(
        read_parquet_polars("database", "string", "ppi_detailed_channels_string_v2.parquet"),
        gene_col="channel_gene_symbol",
        partner_col="channel_partner_gene_symbol",
    )

    aliases = read_parquet_polars("database", "string", "protein_alias_string_v2.parquet")
    results["protein_alias_string"] = aliases.rename({k: v for k, v in {"string_id": "protein_id"}.items() if k in aliases.columns})

    # Partner-role denormalization (automatic): each PPI table references the
    # master table via BOTH protein_id (anchor) and protein_partner_id (partner).
    # The planner only joins the master once on the anchor, so partner-side
    # attributes (protein_size) are invisible. auto_add_partner_attributes scans
    # this DB's schema.json FK metadata, detects the two-FK-same-master pattern,
    # and left-joins the partner's scalar attributes as partner_<attr>. Driven
    # entirely by FK descriptions — no hand-listed columns. Runs AFTER
    # bidirectional expansion so protein_partner_id is the true partner slot.
    auto_add_partner_attributes(results, db="string")

    # Table-unique column names: `partner_protein_size` is injected by auto_add_partner_attributes
    # into all three PPI tables. Rename each to a table-prefixed name so schema_kg FK generator
    # doesn't create spurious cross-table join edges between them.
    for _tbl, _rmap in {
        "ppi_association_string":       {"partner_protein_size": "association_partner_protein_size"},
        "ppi_physical_string":          {"partner_protein_size": "physical_partner_protein_size"},
        "ppi_detailed_channels_string": {"partner_protein_size": "channels_partner_protein_size"},
    }.items():
        _df = results.get(_tbl)
        if _df is not None:
            _present = {o: n for o, n in _rmap.items() if o in _df.columns}
            if _present:
                results[_tbl] = _df.rename(_present)

    return clean_table_dict("string", results)
