
FROM python:3.11-slim

# Create a non-root user
RUN useradd -m myuser

WORKDIR /app
COPY requirements.txt requirements.txt
# COPY resources resources
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
# Make sure files are owned by myuser (so myuser can read/write if needed)
RUN chown -R myuser:myuser /app

# Switch to non-root user
USER myuser

ENV PYTHONPATH=/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8012", "--workers", "4"]